### ISSUE TITLE
Implementation Strategy

### ISSUE THREAD

**Issue by blink1073** [blink1073/juptyerlab-module-federation#20]
- [x] Add `labextensions` handler to `main.py` #25
- [x] Add cli handling for dynamic extensions #37 
- [x] Augment theme handler #30 
- [x] Augment settings handler #28 
- [x] Add handling of index.js #47
- [x] Create full example based on #44 
- [x] Transition to main repos #jupyterlab/8802
- [x] Update to use CLI here #62
